export const DataContent = [
	{
		images: "/images/room/room1.jpg",
		stock: "Sisa 10 Kamar",
		type: "Putra",
		title: "Kost Berandal",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Mami Kos",
		timestamp: "12/02/2023",
	},
	{
		images: "/images/room/room2.jpg",
		stock: "Sisa 2 Kamar",
		type: "Putri",
		title: "Kost Rawa Indah",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kimbe",
		timestamp: "12/02/2023",
	},
	{
		images: "/images/room/room3.jpg",
		stock: "Sisa 5 Kamar",
		type: "Campur",
		title: "Kost Laravel",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Parsinta",
		timestamp: "12/02/2023",
	},
	{
		images: "/images/room/room4.jpg",
		stock: "Sisa 2 Kamar",
		type: "Putra",
		title: "Kost Swifter",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Afrizal",
		timestamp: "12/02/2023",
	},
	{
		images: "/images/room/room5.jpg",
		stock: "Sisa 1 Kamar",
		type: "Superior Room",
		title: "Kost Galgadot",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kang Oban",
		timestamp: "12/02/2023",
	},
	{
		images: "/images/room/room6.jpg",
		stock: "Sisa 5 Kamar",
		type: "Deluxe Room",
		title: "Kost Dewsiui",
		desk: "Jl. Ir Soeakrno Gg.Dharma Bakti Kec. Muara Jawa Ulu Kel. Muara",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Adhan",
		timestamp: "12/02/2023",
	},
];
