export const DataContentHome = [
	{
		images: "/images/room/room1.jpg",
		stock: "Tersisa 10 Kamar",
		type: "Kost Putra",
		title: "Kost Barokah",
		desk: "Jln. Beskalan - Kel. Ngupasan - Kec. Gondomanan - YOGYAKARTA	",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Mami Kos",
		timestamp: "12/02/2023",
		discount: "15%",
		pricelist: 4500000,
	},
	{
		images: "/images/room/room2.jpg",
		stock: "Tersisa 2 Kamar",
		type: "Kost Putri",
		title: "Kost Gupas",
		desk: "Jln. Alun-alun Utara No. Genap - Kel. Ngupasan  - YOGYAKARTA",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kimbe",
		timestamp: "12/02/2023",
		discount: "25%",
		pricelist: 4500000,
	},
	{
		images: "/images/room/room3.jpg",
		stock: "Tersisa 5 Kamar",
		type: "Kost Campur",
		title: "Kost Laravel",
		desk: "Jln. Buahbatu, No. Ganjil 83 dst - Kel. Turangga - Kec. Lengkong - BANDUNG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Parsinta",
		timestamp: "12/12/2023",
		discount: "10%",
		pricelist: 4500000,
	},
	{
		images: "/images/apartemen/room1.jpg",
		stock: "Sisa 12 Kamar",
		type: "Deluxe Room",
		title: "Kost Setara",
		desk: "Jln. Jengger Ayam Jawa Timur - Kec. Lowokwaru - MALANG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Mami Kos",
		timestamp: "12/02/2023",
		discount: "25%",
		pricelist: 4500000,
	},
	{
		images: "/images/apartemen/room2.jpg",
		stock: "Sisa 2 Kamar",
		type: "Junior Suite Room",
		title: "Kost Juanda",
		desk: "Jln. Gardena Jawa Timur - Kec. Lowokwaru - MALANG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kimbe",
		timestamp: "12/02/2023",
		discount: "55%",
		pricelist: 4500000,
	},
	{
		images: "/images/apartemen/room3.jpg",
		stock: "Sisa 5 Kamar",
		type: "Standard Room",
		title: "Kost Sambutan",
		desk: "Jln. Pahlawan, No. Genap 28 - 80 - Kel. Sidokumpul - Kec. Sidoarjo - SIDOARJO",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Parsinta",
		timestamp: "12/02/2023",
		discount: "15%",
		pricelist: 4500000,
	},
];

export const DataContentKost = [
	{
		kostid: "1",
		images: "/images/room/room1.jpg",
		stock: "Tersisa 10 Kamar",
		type: "Kost Putra",
		title: "Kost Barokah",
		desk: "Jln. Beskalan - Kel. Ngupasan - Kec. Gondomanan - YOGYAKARTA	",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Mami Kos",
		timestamp: "12/02/2023",
		discount: "15%",
	},
	{
		kostid: "2",
		images: "/images/room/room2.jpg",
		stock: "Tersisa 2 Kamar",
		type: "Kost Putri",
		title: "Kost Gupas",
		desk: "Jln. Alun-alun Utara No. Genap - Kel. Ngupasan  - YOGYAKARTA",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kimbe",
		timestamp: "12/02/2023",
		discount: "25%",
	},
	{
		kostid: "3",
		images: "/images/room/room3.jpg",
		stock: "Tersisa 5 Kamar",
		type: "Kost Campur",
		title: "Kost Laravel",
		desk: "Jln. Buahbatu, No. Ganjil 83 dst - Kel. Turangga - Kec. Lengkong - BANDUNG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Parsinta",
		timestamp: "12/12/2023",
		discount: "10%",
	},
	{
		kostid: "4",
		images: "/images/room/room4.jpg",
		stock: "Tersisa 2 Kamar",
		type: "Kost Putra",
		title: "Kost Swifter",
		desk: "Jln. Banteng No. Genap 68 dst - Kel. Turangga - Kec. Lengkong - BANDUNG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Afrizal",
		timestamp: "12/02/2023",
		discount: "5%",
	},
	{
		kostid: "5",
		images: "/images/room/room5.jpg",
		stock: "Tersisa 1 Kamar",
		type: "Kost Campur",
		title: "Kost Galgadot",
		desk: "Jln. Sumur Batu I - IV D.K.I. Jakarta  - JAKARTA PUSAT",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kang Oban",
		timestamp: "12/02/2023",
		discount: "35%",
	},
	{
		kostid: "6",
		images: "/images/room/room6.jpg",
		stock: "Tersisa 5 Kamar",
		type: "Kost Putri",
		title: "Kost Tunel",
		desk: "Jln. Suprapto, Letjen, - Kel. Cempaka Baru D.K.I. Jakarta  - JAKARTA PUSAT",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Adhan",
		timestamp: "12/02/2023",
		discount: "45%",
	},
];

export const DataContentApartemen = [
	{
		partid: "1",
		images: "/images/apartemen/room1.jpg",
		stock: "Sisa 12 Kamar",
		type: "Deluxe Room",
		title: "Kost Setara",
		desk: "Jln. Jengger Ayam Jawa Timur - Kec. Lowokwaru - MALANG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Mami Kos",
		timestamp: "12/02/2023",
		discount: "25%",
	},
	{
		partid: "2",
		images: "/images/apartemen/room2.jpg",
		stock: "Sisa 2 Kamar",
		type: "Junior Suite Room",
		title: "Kost Juanda",
		desk: "Jln. Gardena Jawa Timur - Kec. Lowokwaru - MALANG",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Kimbe",
		timestamp: "12/02/2023",
		discount: "55%",
	},
	{
		partid: "3",
		images: "/images/apartemen/room3.jpg",
		stock: "Sisa 5 Kamar",
		type: "Standard Room",
		title: "Kost Sambutan",
		desk: "Jln. Pahlawan, No. Genap 28 - 80 - Kel. Sidokumpul - Kec. Sidoarjo - SIDOARJO",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Parsinta",
		timestamp: "12/02/2023",
		discount: "15%",
	},
	{
		partid: "4",
		images: "/images/apartemen/room4.jpg",
		stock: "Sisa 2 Kamar",
		type: "Junior Suite Room",
		title: "Kost Sungai Dama",
		desk: "Jln. Hang Tuah No. Genap 2 - 18 - Kel. Sidokumpul - Kec. Sidoarjo - SIDOARJO",
		domsil: "Jawa Timur, Sidoarjo",
		author: "Afrizal",
		timestamp: "12/02/2023",
		discount: "15%",
	},
	{
		partid: "5",
		images: "/images/apartemen/room5.jpg",
		stock: "Sisa 1 Kamar",
		type: "Superior Room",
		title: "Kost Karang Asam",
		desk: "Jln. Surya - Kel. Jebres - Kec. Jebres - SURAKARTA (SOLO)",
		domsil: "Jawa Tengah, Solo",
		author: "Kang Oban",
		timestamp: "12/02/2023",
		discount: "15%",
	},
	{
		partid: "6",
		images: "/images/apartemen/room6.jpg",
		stock: "Sisa 5 Kamar",
		type: "Deluxe Room",
		title: "Kost Jamiabul",
		desk: "Jln. Prabangkara - Kel. Jebres - Kec. Jebres - SURAKARTA (SOLO)",
		domsil: "Jawa Tengah, Solo",
		author: "Adhan",
		timestamp: "12/02/2023",
		discount: "15%",
	},
];
